<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.joineryhq.fpptaqb/xml/schema/CRM/Fpptaqb/FpptaquickbooksTrxnCreditmemoLine.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:ad24a1979ccabae853a47ac04a2d56ba)
 */
use CRM_Fpptaqb_ExtensionUtil as E;

/**
 * Database access object for the FpptaquickbooksTrxnCreditmemoLine entity.
 */
class CRM_Fpptaqb_DAO_FpptaquickbooksTrxnCreditmemoLine extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_fpptaquickbooks_trxn_creditmemo_line';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique FpptaquickbooksTrxnCreditmemoLine ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Credit Memo
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $creditmemo_id;

  /**
   * FK to Financial Type
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $ft_id;

  /**
   * Total amount of to be applied to a line item for the given financial type.
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $total_amount;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_fpptaquickbooks_trxn_creditmemo_line';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Fpptaquickbooks Trxn Creditmemo Lines') : E::ts('Fpptaquickbooks Trxn Creditmemo Line');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'creditmemo_id', 'civicrm_fpptaquickbooks_trxn_creditmemo', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'ft_id', 'civicrm_financial_type', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique FpptaquickbooksTrxnCreditmemoLine ID'),
          'required' => TRUE,
          'where' => 'civicrm_fpptaquickbooks_trxn_creditmemo_line.id',
          'table_name' => 'civicrm_fpptaquickbooks_trxn_creditmemo_line',
          'entity' => 'FpptaquickbooksTrxnCreditmemoLine',
          'bao' => 'CRM_Fpptaqb_DAO_FpptaquickbooksTrxnCreditmemoLine',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'creditmemo_id' => [
          'name' => 'creditmemo_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Credit Memo'),
          'where' => 'civicrm_fpptaquickbooks_trxn_creditmemo_line.creditmemo_id',
          'table_name' => 'civicrm_fpptaquickbooks_trxn_creditmemo_line',
          'entity' => 'FpptaquickbooksTrxnCreditmemoLine',
          'bao' => 'CRM_Fpptaqb_DAO_FpptaquickbooksTrxnCreditmemoLine',
          'localizable' => 0,
          'FKClassName' => 'CRM_Fpptaqb_DAO_FpptaquickbooksTrxnCreditmemo',
          'add' => NULL,
        ],
        'ft_id' => [
          'name' => 'ft_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Financial Type'),
          'where' => 'civicrm_fpptaquickbooks_trxn_creditmemo_line.ft_id',
          'table_name' => 'civicrm_fpptaquickbooks_trxn_creditmemo_line',
          'entity' => 'FpptaquickbooksTrxnCreditmemoLine',
          'bao' => 'CRM_Fpptaqb_DAO_FpptaquickbooksTrxnCreditmemoLine',
          'localizable' => 0,
          'FKClassName' => 'CRM_Financial_DAO_FinancialType',
          'add' => NULL,
        ],
        'total_amount' => [
          'name' => 'total_amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Total Amount'),
          'description' => E::ts('Total amount of to be applied to a line item for the given financial type.'),
          'required' => TRUE,
          'precision' => [
            20,
            2,
          ],
          'import' => TRUE,
          'where' => 'civicrm_fpptaquickbooks_trxn_creditmemo_line.total_amount',
          'dataPattern' => '/^\d+(\.\d{2})?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_fpptaquickbooks_trxn_creditmemo_line',
          'entity' => 'FpptaquickbooksTrxnCreditmemoLine',
          'bao' => 'CRM_Fpptaqb_DAO_FpptaquickbooksTrxnCreditmemoLine',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'fpptaquickbooks_trxn_creditmemo_line', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'fpptaquickbooks_trxn_creditmemo_line', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
