<?php

use CRM_Fpptaqb_ExtensionUtil as E;

return array(
  'fpptaqb_use_sync_class' => array(
    'group_name' => 'Fpptaqb Settings',
    'group' => 'fpptaqb',
    'name' => 'fpptaqb_use_sync_class',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => '',
    'title' => E::ts('QuickBooks sync level'),
    'type' => 'String',
    'quick_form_type' => 'Select',
    'default' => 'CRM_Fpptaqb_Sync_Mock',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
      'style' => "width:auto;",
    ),
    'X_options_callback' => 'CRM_Fpptaqb_Util::getSyncClassOptions',
  ),
  'fpptaqb_pmt_deposit_to_account_id' => array(
    'group_name' => 'Fpptaqb Settings',
    'group' => 'fpptaqb',
    'name' => 'fpptaqb_pmt_deposit_to_account_id',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => '',
    'title' => E::ts('QuickBook account for Payments'),
    'type' => 'Int',
    'quick_form_type' => 'Element',
    'default' => NULL,
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
      'style' => "width:auto;",
    ),
    'X_options_callback' => 'CRM_Fpptaqb_Utils_Quickbooks::getAccountOptions',
  ),
  'fpptaqb_sync_wait_days' => array(
    'group_name' => 'Fpptaqb Settings',
    'group' => 'fpptaqb',
    'name' => 'fpptaqb_sync_wait_days',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Days to wait before syncing an invoice or payment'),
    'description' => 'Any contribution or payment will not be synced to QuickBooks until it is this many days old, in order to allow time for corrections. Set to 0 for no delay.',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'default' => 7,
    'html_type' => 'text',
    'X_form_rules_args' => [
      [E::ts('The field "Days to wait before syncing an invoice or payment" is required. Set to 0 for no delay.'), 'required'],
    ],
  ),
  'fpptaqb_minimum_date' => array(
    'group_name' => 'Fpptaqb Settings',
    'group' => 'fpptaqb',
    'name' => 'fpptaqb_minimum_date',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Minimum invoice/payment date'),
    'description' => 'YYYY-MM-YDD: No invoice will be synced if its "Received Date" is less than this date.',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'default' => '4000-01-01',
    'html_type' => 'text',
    'X_form_rules_args' => [
      [E::ts('The field "Minimum invoice/payment date" is required.'), 'required'],
    ],
  ),
  'fpptaqb_quickbooks_consumer_key' => array(
    'group_name' => E::ts('QuickBooks Online Settings'),
    'group' => 'fpptaqb',
    'name' => 'fpptaqb_quickbooks_consumer_key',
    'type' => 'String',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Client ID'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Initial client id retrieved from quickbooks website'),
    'help_text' => E::ts('Initial client id retrieved from quickbooks website'),
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
  'fpptaqb_quickbooks_shared_secret' => array(
    'group_name' => E::ts('QuickBooks Online Settings'),
    'group' => 'fpptaqb',
    'name' => 'fpptaqb_quickbooks_shared_secret',
    'type' => 'String',
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Client Secret'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Initial client secret retrieved from quickbooks website'),
    'help_text' => E::ts('Initial client secret retrieved from quickbooks website'),
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),

  
  'fpptaqb_quickbooks_access_token_expiryDate' => array(
    'group_name' => E::ts('QuickBooks Online Settings'),
    'group' => 'fpptaqb',
    'name' => 'fpptaqb_quickbooks_access_token_expiryDate',
    'type' => 'String',
    'add' => '4.7',
    'default' => 1,
    'title' => E::ts('Access Token Expiry Date'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Expiry date of the current access token'),
    'help_text' => E::ts('Expiry date of the current access token'),
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
      'readonly' => 'true',
    ),
    'quick_form_type' => 'Element',
  ),
  'fpptaqb_quickbooks_refresh_token_expiryDate' => array(
    'group_name' => E::ts('QuickBooks Online Settings'),
    'group' => 'fpptaqb',
    'name' => 'fpptaqb_quickbooks_refresh_token_expiryDate',
    'type' => 'String',
    'add' => '4.7',
    'default' => 1,
    'title' => E::ts('Refresh Token Expiry Date'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Expiry date of the current refresh token'),
    'help_text' => E::ts('Expiry date of the current refresh token'),
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
      'readonly' => 'true',
    ),
    'quick_form_type' => 'Element',
  ),
  'fpptaqb_quickbooks_realmId' => array(
    'group_name' => E::ts('QuickBooks Online Settings'),
    'group' => 'fpptaqb',
    'name' => 'fpptaqb_quickbooks_realmId',
    'type' => 'String',
    'add' => '4.7',
    'default' => '',
    'title' => 'realmId',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('realmId retrieved when got access token'),
    // Omit 'quick_form_type' property to hide from settings form.
    'quick_form_type' => NULL,
  ),
  'fpptaqb_quickbooks_state_token' => array(
    'group_name' => E::ts('QuickBooks Online Settings'),
    'group' => 'fpptaqb',
    'name' => 'fpptaqb_quickbooks_state_token',
    'type' => 'String',
    'html_type' => NULL,
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Current State Token'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('State token generated for user authorization'),
    'help_text' => E::ts('State token generated for user authorization'),
    // Omit 'quick_form_type' property to hide from settings form.
    'quick_form_type' => NULL,
  ),
  'fpptaqb_quickbooks_access_token' => array(
    'group_name' => E::ts('QuickBooks Online Settings'),
    'group' => 'fpptaqb',
    'name' => 'fpptaqb_quickbooks_access_token',
    'type' => 'String',
    'html_type' => NULL,
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Current Access Token'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Access token retrieved after user authorization'),
    'help_text' => E::ts('Access token retrieved after user authorization'),
    // Omit 'quick_form_type' property to hide from settings form.
    'quick_form_type' => NULL,
  ),
  'fpptaqb_quickbooks_refresh_token' => array(
    'group_name' => E::ts('QuickBooks Online Settings'),
    'group' => 'fpptaqb',
    'name' => 'fpptaqb_quickbooks_refresh_token',
    'type' => 'String',
    'html_type' => NULL,
    'add' => '4.7',
    'default' => '',
    'title' => E::ts('Current Refresh Token'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Refresh token retrieved after user authorization'),
    'help_text' => E::ts('Refresh token retrieved after user authorization'),
    // Omit 'quick_form_type' property to hide from settings form.
    'quick_form_type' => NULL,
  ),
);